### PR TITLE
Added the option to change the position of the text inside tooltip bo…

### PR DESCRIPTION
**Pull request by Uraskin**
…x, when overlay happened.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
I don't understand the use-case of this feature,
Please write a descriptive description, and define the problem and then introduce your solution.
Thanks!

**Comment by Uraskin** [comment]
> I don't understand the use-case of this feature,
> Please write a descriptive description, and define the problem and then introduce your solution.
> Thanks!

My use-case I ran into:  I setup option fitInsideHorizontally = true, then tooltipBox will be align to the right or left side. But text inside box always align to center, sometimes I need text be align to the left/right too.

**Comment by imaNNeoFighT** [comment]
I understand the problem,
but this approach (having a `tooltipTextAlignCenter`) is not customizable enough.
I have a better approach to handle this in my head.

Inside the [LineTooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetooltipitem), we can add a property called textAlign (from [TextAlign](https://api.flutter.dev/flutter/dart-ui/TextAlign-class.html) enum), then we can use it in our painter, instead of hard-coded `Align.center` (check [line_chart_painter:1134](https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/line_chart/line_chart_painter.dart#L1134)).
It is so better for customizability.

Your use-case: 
then you can set `Alignment.left` for your first spot, and `Alignment.right` for your last spot.

Benefits: 
Now other people can use it freely and implement their use-cases without needing to add a new property or change it.

Let me know what you think.

Thanks for contributing!

**Comment by Uraskin** [comment]
> I understand the problem,
> but this approach (having a `tooltipTextAlignCenter`) is not customizable enough.
> I have a better approach to handle this in my head.
> 
> Inside the [LineTooltipItem](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetooltipitem), we can add a property called textAlign (from [TextAlign](https://api.flutter.dev/flutter/dart-ui/TextAlign-class.html) enum), then we can use it in our painter, instead of hard-coded `Align.center` (check [line_chart_painter:1134](https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/line_chart/line_chart_painter.dart#L1134)).
> It is so better for customizability.
> 
> Your use-case:
> then you can set `Alignment.left` for your first spot, and `Alignment.right` for your last spot.
> 
> Benefits:
> Now other people can use it freely and implement their use-cases without needing to add a new property or change it.
> 
> Let me know what you think.
> 
> Thanks for contributing!

I tried to use you're advise, but this did not work. Or maybe I have made something wrong.
So, property TextAling at line_chart_painter:1134, did not affect to positioned of tooltip text. If i changed it to left/right - nothing happened.
In my realisation I calculate position of tooltip text.

**Comment by imaNNeoFighT** [comment]
Hmm, okay, 
what if we only use Alignment as a data holder?
I mean you can do your right calculations if the alignment is Alignment.right, and left calculations. if the alignment is left.
Or maybe we can have an enum for aligning it only left or right.

**Comment by imaNNeoFighT** [comment]
I'm gonna close this. Because I didn't get any answer from you.
Thanks!

**Pull request closed without merging**
