### PR TITLE
Fix a NAN crash for HTML web renderer

### PR DESCRIPTION
**Pull request by shalehaha**
cc @imaNNeoFighT

We are seeing a NAN crash when used it with HTML web renderer. I have tracked it down and found the line of code that is causing the problem.
I'm not quite familiar with the code base, so I just made a quick fix for it which is easiest for me. There might be a more elegant way to fix it, in that case, you can just close my PR.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Hi. Can you please send me a stack trace or something like that?

**Comment by imaNNeoFighT** [comment]
Is there a way to reproduce it?

**Comment by svki0001** [comment]
I have the same issue for mobile browsers, when using SideTitles in a LineChart.

**Comment by imaNNeoFighT** [comment]
This issue has been fixed in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0).
For more information, check here:
https://github.com/imaNNeoFighT/fl_chart/blob/42e9863589072c33c0ae1bd9418da698c98eb075/lib/src/utils/utils.dart#L138-L140

**Pull request closed without merging**
