### PR TITLE
Add option to enable rounded corners for pie charts

### PR DESCRIPTION
**Pull request by himamis**
Let me know if you find this useful:
This adds the option to set the edges of a pie chart rounded.

### CODE REVIEW

**Comment by himamis** [comment]
Screenshot 2022-03-27 at 13 37 45
The idea was to add rounded corners to the sections themselves.
I sometimes get problems with NaN values in the path with this code, which tries to cut out these rounded corners.
Do you have any other idea how to approach this?

**Comment by imaNNeoFighT** [comment]
> Screenshot 2022-03-27 at 13 37 45 To achieve this, I pass 10.0 radius to PieChartSectionData The idea was to add rounded corners to the sections themselves. I sometimes get problems with NaN values in the path with this code, which tries to cut out these rounded corners. Do you have any other idea how to approach this?

This is not a pie chart. To handle this type of chart, we can use a curved line only.
Now we are creating a complicated path that is hard to apply roundness to it.

**Comment by imaNNeoFighT** [comment]
Any progress on this PR?

**Comment by Wizzel1** [comment]
@imaNNeoFighT is it possible to create such a chart with your package?

**Comment by hieplee2997** [comment]
@imaNNeo any update on this issue

**Comment by imaNNeo** [comment]
> @imaNNeo any update on this issue

You can follow #1175

**Pull request closed without merging**
