### PR TITLE
fix horizontal over position

### PR DESCRIPTION
**Pull request by 666nana666**
fix over position in top and bottom titles

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Please tell me more about it.

**Comment by 666nana666** [comment]
sorry just replied

i will give result about it 

**Before**
image

**After**
image

in this case i need value highest and value lowest but if the value at first value or last value the titles verticals will over position like pic number one so i fixed 

sorry my english is bad hope you undrastand

**Comment by imaNNeoFighT** [comment]
Can you give me your reproducible code?

**Comment by 666nana666** [comment]
sure,but i need time.

**Pull request closed without merging**
