### PR TITLE
Sort Scatter Spots with radius.

### PR DESCRIPTION
**Pull request by prajwal27**
#930

### CODE REVIEW

**Comment by prajwal27** [comment]
@imaNNeoFighT  this should be a quick merge?

**Comment by imaNNeoFighT** [comment]
Hi. Can you please update the CHANGELOG.md to mention this improvement?

**Comment by prajwal27** [comment]
@imaNNeoFighT  updated CHANGELOG.

**Comment by imaNNeoFighT** [comment]
image

I cannot merge.
It seems you need to rebase your branch (instead of merging)

**Comment by prajwal27** [comment]
@imaNNeoFighT  can you check now?

**Comment by imaNNeoFighT** [comment]
Thanks for contributing!

**Pull request merged**
