### PR TITLE
style: dart format with width 100

### PR DESCRIPTION
**Pull request by shamilovtim**
dart formatter ran on the whole project with width 100

### CODE REVIEW

**Comment by shamilovtim** [comment]
Manually fixing some trailing commas right now. WIP

**Comment by shamilovtim** [comment]
All set with this

**Comment by imaNNeoFighT** [comment]
How you sure about the 100 width?
is this a regular size?

**Comment by shamilovtim** [comment]
@imaNNeoFighT It's a common opinion that 80 is way too small for modern screens

**Comment by imaNNeoFighT** [comment]
Okay, I will review it, give me some time bro :)

**Comment by shamilovtim** [comment]
here is 100 on standard macbook pro resolution with an emulator open on the same screen
Screen Shot 2020-01-17 at 4 32 04 PM

**Comment by shamilovtim** [comment]
here is the same area with 80. most of the screen is unused. i don't know why so many formatters ship with 80 as a default but its definitely a minority opinion to have so little space used i think.
Screen Shot 2020-01-17 at 4 39 48 PM

**Comment by shamilovtim** [comment]
deleted my last comment. i think this image is a good example of the way 80 does weird squishing behavior. 

Screen Shot 2020-01-17 at 4 42 49 PM

**Comment by imaNNeoFighT** [comment]
Thanks!

**Pull request merged**
