### PR TITLE
Improvement/slidetitle textdirection

### PR DESCRIPTION
**Pull request by NaarGes**
I'm using Persian language with this package and it didn't support RTL languages in side titles and tooltips. So I added optional `textDirection` property with `TextDirection.ltr` default value for side titles and tooltip.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
We have added `textAlign` property in #601.
It will be great if you write a description.
I think that's why I didn't check this PR.

**Comment by NaarGes** [comment]
I'm sorry that I forgot to write a description, I wrote it then.

I saw the commits of #601 pull request. It doesn't meet my needs. `TextAlign` is not the same as `TextDirection`. Text align indicates where the text is located within an element. But text direction specified which way the text flows, right-to-left or left-to-right. 

In my case I wanted to tag bottom titles with Persian dates like `۲۷ اسفند`, and it didn't displayed correctly without `textDirection` property.

**Comment by imaNNeoFighT** [comment]
Got it. You are right!

**Comment by imaNNeoFighT** [comment]
Can you please rebase your changes with the dev and let me know?
I highly suggest you make a new branch, because we have made a lot of changes since it opened.

**Comment by imaNNeoFighT** [comment]
`textDirection` property added in SideTitles, AxisTitles and Tooltips in [0.35.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.35.0)

**Pull request closed without merging**
