### PR TITLE
WIP: added horizontal bar chart

### PR DESCRIPTION
**Pull request by juumixx**
Added horizontal bar charts.

To be able to reuse the bar_chart_data, I changed the naming of `y` and `x` to in the bars and groups to `value`, because in the horizontal bar they would be flipped.
Also, horizontal bars have the ability to put text onto the bar, which is saved in `BarChartRodData.title`.
We could also draw this text 90° rotated on the vertical bar chart to be consistent, but this is not implemented yet.

I added a temporary example here

What do you think?

PS: it would be really cool if we could format the code according to [effective dart](https://dart.dev/guides/language/effective-dart/style), I just noticed there is a lot of whitespace change in the diff which is unrelated :(

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Wow, there are a lot of changes.
I'm so happy to see that, it fixes #113 
I will review it ASAP, give me some time dude :)
And about the code format, I'm totally with you but do not reformat in a feature PR ever, it makes the review process hard, 
make a new PR, and do all reformat in that, I will merge it ASAP.
Thanks!

**Comment by scostagabriel** [comment]
@imaNNeoFighT , thank you for this amazing library, it's really awesome!

Do you have any expectations about when to merge this PR?

**Comment by berengere13** [comment]
Hello,

Have you any news about this feature ? Our team is very interested !

Thanks you very much.

**Comment by imaNNeoFighT** [comment]
Hello, I think it's not gonna implement soon, 
because we are so busy, can make your hands dirty and try to implement it.
Thanks, regards!

**Comment by Nazacheres** [comment]
@imaNNeoFighT Actually similar results can be achieved, just by wrapping BarChart with RotatedBox. What would be good is just enable rotation for titles and tooltips :) That's a small change.

**Comment by imaNNeoFighT** [comment]
Okay, make separate issues for them to follow up.
Thanks for suggesting!

**Comment by liasica** [comment]
> @imaNNeoFighT Actually similar results can be achieved, just by wrapping BarChart with RotatedBox. What would be good is just enable rotation for titles and tooltips :) That's a small change.

tooltips rotation how?

**Pull request closed without merging**
