### PR TITLE
Improvement/context wrapper

### PR DESCRIPTION
**Pull request by imaNNeoFighT**
We implemented ContextWrapper class to proxy all canvas draw functions through it.
It makes our draw system testable.

### CODE REVIEW

**Comment by mhmdanas** [comment]
Why not use `Canvas` like before and mock it in tests using [mockito](https://pub.dev/packages/mockito)?

**Comment by imaNNeoFighT** [comment]
Hmm I think you are right, can you please try it out and Implement a draw function's test?

**Comment by mhmdanas** [comment]
I'll give it a stab tomorrow, but please bear in mind that I am not familiar with fl_chart's internals, so this might take more time than expected.

**Comment by mhmdanas** [comment]
I just found an issue with my approach. We will have to mock `TextPainter` somehow, but that's not passed to the class; it's constructed inside of its methods. Maybe we should stick to your `CanvasWrapper` approach but combine it with `mockito` to reduce boilerplate. How about that?

**Pull request merged**
