### PR TITLE
Feature/pie chart gradient

### PR DESCRIPTION
**Pull request by SomeoneAndNoone**
https://github.com/imaNNeoFighT/fl_chart/issues/166

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Please update your branch.
There are 90 commits in your PR

**Comment by SomeoneAndNoone** [comment]
I changed base from master to dev. But not sure why you are saying that. Almost all the commits are yours except the last 9. My branch is already up-to-date with dev

**Comment by imaNNeoFighT** [comment]
There's something wrong.

image

**Comment by imaNNeoFighT** [comment]
Our branching approach changed due to the problem you have faced. (Read more about it here #938).
Sorry about that I had to do that.
Now you need to make your branch from `master`.

Follow this guide to re-create your PR:
1. Checkout to `master` branch and pull it.
2. Create a new branch
3. Cherry-pick your commits from this old branch into your new branch.
4. Then push it and make a new PR. 
5. Mention the old PR in your new PR.

**Comment by ashishbeck-zeeve** [comment]
Hello, is there any scope for having this merged?

**Pull request closed without merging**
