### PR TITLE
feat: Gradient Pie Chart

### PR DESCRIPTION
**Pull request by hbdejesus**
- Add the support for gradient pie chart by making the color a list of colors
- Update Documentation
- Update Samples

This implementation is almost the same with BarChart

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Hi. I've pushed a commit to just format the code with 80 characters.
Can you please resolve the conflicts?

**Comment by hbdejesus** [comment]
> Hi. I've pushed a commit to just format the code with 80 characters.
> Can you please resolve the conflicts?

Updated

**Comment by imaNNeoFighT** [comment]
Still there are two conflicts.

**Comment by hbdejesus** [comment]
> Still there are two conflicts.

Updated

**Comment by hbdejesus** [comment]
Would be nice if you could check this @imaNNeoFighT 🙇

**Comment by BrunoJurkovic** [comment]
This is much needed, thanks to @hbdejesus for this amazing feature :)), using your repo in our project until this gets merged.

**Comment by BrunoJurkovic** [comment]
On second thought, there seems to be an issue with the drawing. See the image below, occurred when I set a gradient and a radius.

https://imgur.com/a/toJNUia

**Comment by imaNNeoFighT** [comment]
Any update on this PR from the creator?

Guys, can you link your issues here? What kind of gradient do you want?

**Pull request closed without merging**
