### PR TITLE
Add possibility to specify gradients for pie chart

### PR DESCRIPTION
**Pull request by himamis**
This adds the possibility to specify gradients through the PieChartSectionData.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Can you please use `setColorOrGradient` extension function for handling gradients? Like what we did here:
https://github.com/imaNNeoFighT/fl_chart/blob/fd3a8b6e6143609e7bdc58e61b03b93692c47e4b/lib/src/chart/bar_chart/bar_chart_painter.dart#L331-L336

**Comment by himamis** [comment]
Yes, I now use the extension function provided.

**Comment by imaNNeoFighT** [comment]
Great!
Can you please use this wonderful gradient on one of our samples to demonstrate it to our users?
Also please don't forget to update bar_chart.md file and also write the changelog in CHANGELOG.md file.

Thanks!

**Comment by himamis** [comment]
Thanks, all done.

**Comment by imaNNeoFighT** [comment]
Holly crap. We forgot to continue this branch.
Please rebase your branch and fix the formatting issue (read the [CONTRIBUTING.md](https://github.com/imaNNeoFighT/fl_chart/blob/master/CONTRIBUTING.md)).

**Pull request closed without merging**
