### PR TITLE
Override toString method for FlSpot

### LINKED ISSUE #469: [Question][LineChart][FlSpot] How can I print x and y values of FlSpots?
I would like to know how to print the x and y values for FlSpots from a List of FlSpots.
Iman posted an answer at this link: 
https://stackoverflow.com/questions/60281061/how-to-assign-an-array-to-spots-in-fl-chart-in-flutter/61987521#61987521

When I try to print the FlSpot values from the answer Iman gave with "print(spots)", my console returns: 
`I/flutter (19814): [FlSpot, FlSpot, FlSpot, FlSpot, FlSpot, FlSpot, FlSpot]`

How can I instead receive the x and y coordinates of each FlSpot and not just the data type? It would be helpful to know how to do this so I can double-check my FlSpot values in the Console during testing.

### PR DESCRIPTION
**Pull request by LondonTran**
Allows printing of X and Y values for FlSpot instead of data type by default. Resolves #469  
My first pull request ever and participating in Hacktoberfest!
- London Tran

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Congratulation on your first contribution.
Thanks!

**Comment by imaNNeoFighT** [comment]
We will publish a new version containing this change ASAP.

**Comment by LondonTran** [comment]
Thank you! :)

**Comment by imaNNeoFighT** [comment]
Noproblem

**Pull request merged**
