### PR TITLE
Bugfix/piechart resize

### PR DESCRIPTION
**Pull request by xinoxapps**
Fixes issue #514 which can occur when the PieChart resizes in a Sliver.

### CODE REVIEW

**Comment by bdlukaa** [comment]
When can this be merged?

**Comment by imaNNeoFighT** [comment]
Now!

**Comment by bdlukaa** [comment]
Now a different error is thrown. `Another exception was thrown: A build function returned null.`.

Instead of `return null;`, it should be `return SizedBox();`

**Review by bdlukaa — COMMENTED** [review]
`A build function returned null.` `badgeWidgets` is returning null

**Pull request merged**
