### PR TITLE
Migrated the third PieChart example to null safety

### PR DESCRIPTION
**Pull request by 4amVim**
As null safety is now de-facto branch most users are using, the examples should work on it out-of-the-box.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Github shows  Files changed 0

**Comment by 4amVim** [comment]
Apologies for that, fixed it now. 
P.S. This is a duplicate of [PR #632](https://github.com/imaNNeoFighT/fl_chart/pull/632)

**Comment by imaNNeoFighT** [comment]
Great!

**Comment by imaNNeoFighT** [comment]
Thanks for contributing!

**Pull request merged**
