### PR TITLE
Fix some mistakes in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mhmdanas**

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
I don't know why it has been failed :)))

**Comment by mhmdanas** [comment]
It's failing because of #296. I dtill don't know why it isn't working.

**Comment by imaNNeoFighT** [comment]
Hi, there was a problem with `master`, that's why this branch is failed.
I've just fixed the problem, please update your branch with master,
Thanks.

**Comment by mhmdanas** [comment]
Done!

**Comment by imaNNeoFighT** [comment]
And may I ask you to change the target to the dev branch?

**Comment by imaNNeoFighT** [comment]
I've merged it, and thanks for contributing.

**Pull request merged**
