### PR TITLE
Feature: Image annotations

### PR DESCRIPTION
**Pull request by shamilovtim**
The purpose of this PR is to add the ability to annotate a line (whether it has a visible width or not) with an image or an icon. The user on his side needs to load the image as a future, which is standard Flutter stuff. 

**There are some whitespace changes. We should consider adding a git hook to dartfmt and enforce style rules. Unfortunately the last PR submitter did not use our formatter settings probably because he has an overriding global VSCode setup or uses a different editor.** 

Screen Shot 2020-01-27 at 2 36 01 PM

### CODE REVIEW

**Comment by shamilovtim** [comment]
This PR is tracking dev branch

**Comment by imaNNeoFighT** [comment]
Thanks, man, and again, apologize for my delay.

**Comment by imaNNeoFighT** [comment]
@shamilovtim Did you update the sample image?

**Comment by shamilovtim** [comment]
Hey, no problem! Thank you. Yes the sample image is in here with an egg and the two label examples

**Pull request merged**
