### PR TITLE
docs(example/changes_color_property):

### PR DESCRIPTION
**Pull request by erisanolasheni**
Changes the `Color color` property in `BackgroundBarChartRodData` to `List<Color> colors`. 

Since this property has been changed in the package updates, these examples can be misleading for starters.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
You should provide `color` property. There is no `colors` property at this time.
That's why the CI is failed.

**Comment by erisanolasheni** [comment]
@imaNNeoFighT This is strange though, as I am using this plugin on my app now and there is no `color` property (anymore) in the `BackgroundBarChartRodData` class but `colors` with `List` of `Color`'s, here is my implementation here:
```dart
BackgroundBarChartRodData(
            show: true, toY: 20, colors: barBackgroundColors),
)
```
`List barBackgroundColors = [Color(0xffD04537).withAlpha(25)]`

**Comment by imaNNeoFighT** [comment]
What version are you using?

**Comment by erisanolasheni** [comment]
Oh, sure you are right. I see that I am using an old version, I have switched to a latest version now, thanks.

**Pull request closed without merging**
