### PR TITLE
Make example compile with sound nullsafety 

### PR DESCRIPTION
**Pull request by porfirioribeiro**
With some small adjusts by reading the analyzer errors i managed to get the example to compile with sound null safety

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Hi @porfirioribeiro.
Sorry for this conflict, but we are working on null-safety currently.
Follow it here: #579. We are going to merge it ASAP.
Because Flutter stable branch requires null-safety.

**Comment by porfirioribeiro** [comment]
No worries, just wanted to help.

I based my PR on #579 not master.

**Comment by imaNNeoFighT** [comment]
Sorry, I didn't know you based it on #579.
BTW accept my apologies. I will try to find a way to prevent these kinds of conflicts.

**Comment by porfirioribeiro** [comment]
It's ok, thanks for your work on this. I'm current evaluating this library for our project as an alternative to google/charts that seems to be unmaintained. Will try to contribute back, if i'm able to

**Comment by imaNNeoFighT** [comment]
Pleasure is mine.

**Pull request closed without merging**
