### PR TITLE
rounded bars with clipping for stack items

### PR DESCRIPTION
**Pull request by juumixx**
Warning: API change! But default behaviour when `isRound` wasn't used does not change.
Fixes https://github.com/imaNNeoFighT/fl_chart/issues/147

### CODE REVIEW

**Comment by juumixx** [comment]
I found an issue with the stack drawing, update coming soon.

**Comment by imaNNeoFighT** [comment]
Okay don't hurry

**Comment by juumixx** [comment]
fixed it now.

**Comment by imaNNeoFighT** [comment]
I've reviewed it,
it is as perfect as possible.
Thank you!

**Comment by imaNNeoFighT** [comment]
I've just changed the target branch to [v0.6.4](https://github.com/imaNNeoFighT/fl_chart/tree/v0.6.4) branch because we should not push them into the master directly.

**Comment by imaNNeoFighT** [comment]
I think we should have a `dev` branch.

**Comment by juumixx** [comment]
Thanks! I'm fine with having a dev branch.

**Comment by imaNNeoFighT** [comment]
Ok I will make the dev branch, and because it has BREAKING CHANGES, I will bring it in the 0.7.0 version (with some more features)

**Pull request merged**
