### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by mhmdanas**

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Too many typo mistakes :))
I didn't know them,
thank you btw.

**Comment by mhmdanas** [comment]
You're welcome! This is not a trivial project; some typos are to be expected. I didn't read all the files, of course; I used a handy program called cspell. If you are a Visual Studio Code user, there is an extension that uses this program to check your files' spelling.

Hope you find this advice helpful!

**Comment by mhmdanas** [comment]
Sorry, this PR should have been against `dev`, right?

**Comment by imaNNeoFighT** [comment]
Yes, I did my best to prevent typos, but they were unavoidable.
No, these kinds of changes, don't need to merge in dev then merge in master,
because the will not break anything and they don't need any bump version.
Thanks!

**Pull request merged**
