### PR TITLE
Fix #1013 - maintain backward compatiblity

### LINKED ISSUE #1013: App crashing: Method 'addPostFrameCallback' can not be called on 'WidgetsBinding?'
image

../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.50.5/lib/src/chart/pie_chart/pie_chart.dart:42:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^

I am using flutter 2.8.1 and can not upgrade anytime soon due to company policy.

There is a solution?

### PR DESCRIPTION
**Pull request by imujtaba8488**

### CODE REVIEW

**Comment by shabbyplace** [comment]
This isn't the best approach to maintain backward compatibility. [Look](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code) at the recommended approach by the flutter team.

**Comment by imujtaba8488** [comment]
> This isn't the best approach to maintain backward compatibility. [Look](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code) at the recommended approach by the flutter team.

@shabbyplace yup -- you're right. Thanks for the reference - fixed and pushed!

**Comment by imaNNeoFighT** [comment]
Thank you guys
I will merge it ASAP

**Comment by imaNNeoFighT** [comment]
Fixed in [0.50.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.50.6) Please check it out.

**Pull request merged**
