### PR TITLE
Changes: Tap Gesture added;

### PR DESCRIPTION
**Pull request by dipendra-sharma**
Tap Gesture Added along with Long press interaction. Now user can interact with the chart via just tapping anywhere in the chart.

### CODE REVIEW

**Comment by akdu12** [comment]
Can you approve this?

**Comment by imaNNeoFighT** [comment]
Ok, I will review it

**Comment by akdu12** [comment]
if you can merge so we can start using it, will be awesome

**Comment by imaNNeoFighT** [comment]
This is not qualified to be merged,
I said what's wrong.

**Comment by imaNNeoFighT** [comment]
The feature is added in [0.1.6](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.1.6) by this pull request: #57

**Comment by imaNNeoFighT** [comment]
Then I will close it,
Thanks, Best Regards

**Pull request closed without merging**
