### PR TITLE
Refactor utils code

### PR DESCRIPTION
**Pull request by mhmdanas**
If I changed the behavior by mistake or anybody disagrees with the refactors, please feel free to tell me.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
It seems good,
let me check it.
Thanks in advance!

**Comment by mhmdanas** [comment]
Is this gonna be merged?

**Comment by imaNNeoFighT** [comment]
Merged, Sorry for the delay!
Thanks for contributing.

**Comment by mhmdanas** [comment]
No worries!

**Pull request merged**
