### PR TITLE
Refactoring BarChartSample3.

### PR DESCRIPTION
**Pull request by bakatsuyuki**
I tried to refactor BarChartSample3. Would you please check it?

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Hi. please set your target branch to `dev` and rebase your branch.
(I think there is a minor conflict with our `dev` branch).

Thanks!

**Comment by bakatsuyuki** [comment]
@imaNNeoFighT I fixed it. Please check it again!

**Comment by imaNNeoFighT** [comment]
It seems your branch has conflicts.
I suggest you pull the dev branch and make your changes again.

**Comment by bakatsuyuki** [comment]
スクリーンショット 2021-08-22 14 51 35
My branch looks like having no conflicts for me.🤔
I pulled the dev branch again. How is it?

**Comment by imaNNeoFighT** [comment]
I see this message:

image

Please checkout into `master` and delete your local `dev` branch (using `git branch -D dev`).
Then fetch all branches again (using `git fetch --all`)
Now your `dev` branch is in the latest state. Then go and rebase your branch with new `dev`.

**Comment by bakatsuyuki** [comment]
@imaNNeoFighT 
Thank you. Maybe I understood but I think it's better to remake the pull request. So I close it.

**Pull request closed without merging**
