### PR TITLE
This adds support for persisting the touch indicator and tooltip after a touch event is complete

### PR DESCRIPTION
**Pull request by dazza5000**

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
How we should clear the indicators if `persistIndicatorsAndTooltips` is true?

**Comment by dazza5000** [comment]
We could make a clearIndicators method

**Comment by imaNNeoFighT** [comment]
I think we need to clear indicators when the user tapped on nothing. 
What you think?

**Comment by dazza5000** [comment]
I like the idea, do we have a callback / way to determine if the user
didn't tap on anything?

**Comment by imaNNeoFighT** [comment]
We've handled something like this in the PieChartSample2,
please take a look.

##### Sample 2 ([Source Code](/example/lib/scatter_chart/samples/scatter_chart_sample2.dart))

**Comment by shamilovtim** [comment]
FYI: in our use case we don't want them cleared at all. We want wherever the user tapped last to persist.

**Pull request closed without merging**
