### PR TITLE
Add ability to use ExtraLinesData in the BarChartData

### PR DESCRIPTION
**Pull request by NikitaPipita**
Resolves issue #476

- Moved ExtraLinesData class and related classes from line_chart_data.dart to axis_chart_data.dart;
- Moved drawExtraLines function from LineChartPainter class to AxisChartPainter class;
- Added extraLinesData variable to AxisChartData and BarChartData constructors.

### CODE REVIEW

**Comment by FriendlyNeighbor** [comment]
Waiting for this update

**Comment by imaNNeoFighT** [comment]
Hi. Please resolve conflicts and update your branch. Then I will review it ASAP.

**Comment by santiracca** [comment]
Hi! any updates when this will be merged?

**Comment by JoshMart** [comment]
Any reason this PR was closed? I could use this feature on charts I am creating. Perhaps I or someone else can continue this if we know why it was closed?

**Comment by imaNNeoFighT** [comment]
I closed this PR because the contributor is not responsive.

**Comment by JoshMart** [comment]
Thanks. I've picked up this work in a fork using these PRs as a starting point, for anyone interested.

**Comment by imaNNeoFighT** [comment]
It would be great if you mention this PR in your new PR.
Thanks

**Pull request closed without merging**
