### PR TITLE
Add possibility to set line join

### PR DESCRIPTION
**Pull request by himamis**
This pull request adds the possibility to set the line join from miter to round.

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
Great! Please update the line_chart.md file to add this property.
Also, don't forget to update the CHANGELOG.md

**Comment by imaNNeoFighT** [comment]
Can you please update the changelog file?

**Comment by himamis** [comment]
Yes. Should I increase minor version by one?

**Comment by imaNNeoFighT** [comment]
There is no need to specify a version. As we mentioned in the [contributing guide](https://github.com/imaNNeoFighT/fl_chart/blob/master/CONTRIBUTING.md#changelog) 

> Most of the time, there will be a [newVersion](https://github.com/imaNNeoFighT/fl_chart/blob/master/CHANGELOG.md#newversion) tag at the top of the CHANGELOG.md file in the master branch. If it doesn't exist, you can write it and write your change below that.

Yesterday I added the newVersion tag on top of our CHANGELOG.md. You just need to rebase your branch with the master.

**Comment by imaNNeoFighT** [comment]
Whenever we feel that it's time to make a release, we decide about the version.

**Comment by himamis** [comment]
Thanks for the clarification, I have added it to the changelog and the documentation.

**Comment by imaNNeoFighT** [comment]
We're good to go.
Please write some unit tests to cover what you added.

**Comment by imaNNeoFighT** [comment]
Thanks for contributing!

**Pull request merged**
