### PR TITLE
0.8.5

### PR DESCRIPTION
**Pull request by imaNNeoFighT**

### CODE REVIEW

**Comment by shamilovtim** [comment]
I think this broke hot reload. I keep getting random errors when I try to save. On a a full refresh / build it's fine but as soon as I try to save I get the error.

image
image

**Comment by shamilovtim** [comment]
@imaNNeoFighT Have tried to flutter clean and remove the app from my device as well. It only seems to help for the first save. Very weird. This is happening both in my project and in the samples of the fl_chart

**Comment by shamilovtim** [comment]
Related #251

**Comment by imaNNeoFighT** [comment]
Hi @shamilovtim,
Let's continue talking on the issue.

**Pull request merged**
